export const  LOADER_MODULE='LOADER_MODULE/'; //namespace
export const  SET_SHOW_LOADER = 'SET_SHOW_LOADER';//mutations
export const  SET_LOADER_MSG='SET_LOADER_MSG'; //mutations
export const  GET_SHOW_LOADER = 'GET_SHOW_LOADER'; //getters
export const  GET_LOADER_MSG='GET_LOADER_MSG';// getters
export const  DISPLAY_LOADER ='DISPLAY_LOADER';//actions
export const  HIDE_LOADER ='HIDE_LOADER';//actions


export const ORDERLIST_MODULE='ORDERLIST_MODULE/';//namespace
export const ORDERLIST_SET_CURRENTTAB='ORDERLIST_SET_CURRENTTAB';//action
export const ORDERLIST_GET_CURRENTTAB='ORDERLIST_GET_CURRENTTAB';//action
export const ORDERLIST_CURRENTTAB='ORDERLIST_CURRENTTAB';//mutations
export const ORDERLIST_GET_LIST='ORDERLIST_GET_LIST';//getters
export const ORDERLIST_LOAD_LIST='ORDERLIST_LOAD_LIST';//action
export const ORDERLIST_CUSTOMER_ORDERS='ORDERLIST_CUSTOMER_ORDERS';//action

export const ORDERLIST_ADD_TO_LIST='ORDERLIST_ADD_TO_LIST';//mutations
export const ORDERLIST_SHOWMORE_LIST='ORDERLIST_SHOWMORE_LIST'//mutations
export const ORDERLIST_SET_CURRENT_SELECTED='ORDERLIST_SET_CURRENT_SELECTED'//mutations
export const ORDERLIST_GET_CURRENT_SELECTED='ORDERLIST_GET_CURRENT_SELECTED'//getters
export const ORDERLIST_SELECT_CURRENT='ORDERLIST_SELECT_CURRENT'//action
export const ORDERLIST_SET_ALL_ORDER_MULITCHECKED='ORDERLIST_SET_ALL_ORDER_MULITCHECKED'//mutations
export const ORDERLIST_GET_ALL_ORDER_MULITCHECKED='ORDERLIST_GET_ALL_ORDER_MULITCHECKED'//getters
export const ORDERLIST_MULITCHECKED='ORDERLIST_MULITCHECKED'//action
export const ORDERLIST_MULITUNCHECKED='ORDERLIST_MULITUNCHECKED'//action
export const ORDERLIST_SET_MULITCHECKED='ORDERLIST_SET_MULITCHECKED'//mutations
export const ORDERLIST_RESET_MULITCHECKED='ORDERLIST_RESET_MULITCHECKED'//actions
export const ORDERLIST_SORT='ORDERLIST_SORT'//action
export const ORDERLIST_GET_SORT='ORDERLIST_GET_SORT'//getters
export const ORDERLIST_SET_SORT='ORDERLIST_SET_SORT'//mutations
export const ORDERLIST_SET_LIMIT='ORDERLIST_SET_LIMIT'//mutations
export const ORDERLIST_RESET_ORDERLIST='ORDERLIST_RESET_ORDERLIST'//mutations
export const ORDERLIST_SET_LOADERMSG='ORDERLIST_SET_LOADERMSG'//mutations
export const ORDERLIST_LOADERMSG='ORDERLIST_LOADERMSG'//action
export const ORDERLIST_FILTER='ORDERLIST_FILTER'//action
export const ORDERLIST_SET_FILTER='ORDERLIST_SET_FILTER'//mutations
export const ORDERLIST_GET_FILTER='ORDERLIST_GET_FILTER'//getters
export const ORDERLIST_CANCEL_ORDERS='ORDERLIST_CANCEL_ORDERS'//action
export const ORDERLIST_MARK_AS_LATE='ORDERLIST_MARK_AS_LATE'//action
export const ORDERLIST_UPDATE_STATUS='ORDERLIST_UPDATE_STATUS'//mutations
export const ORDERLIST_REMOVE_ORDERS='ORDERLIST_REMOVE_ORDERS'//mutations
export const ORDERLIST_LOAD_TAB='ORDERLIST_LOAD_TAB'//action
export const ORDERLIST_UPDATE_SUGGESTED_DELIVERY_DATE='ORDERLIST_UPDATE_SUGGESTED_DELIVERY_DATE'//mutations
export const ORDERLIST_NEW_DELIVERY_DATE=''//mutations


export const TOASTER_MODULE='TOASTER_MODULE/';//namespace
export const TOASTER_ADD_TOAST='TOASTER_ADD_TOAST';//mutations
export const TOASTER_REMOVE_TOAST='TOASTER_REMOVE_TOAST';//mutations
export const TOASTER_MESSAGE='TOASTER_MESSAGE';//action
export const TOASTER_GET_ALL='TOASTER_GET_ALL';//getters


export const ORDERDETAIL_MODULE='ORDERDETAIL_MODULE/';//namespace
export const ORDERDETAIL_GET_DETAILS='ORDERDETAIL_GET_DETAILS'//getters
export const ORDERDETAIL_LOAD_DETAIL='ORDERDETAIL_LOAD_DETAIL';//action
export const ORDERDETAIL_SET_LOADER='ORDERDETAIL_SET_LOADER';//mutations
export const ORDERDETAIL_SET_DETAILS='ORDERDETAIL_SET_DETAILS'//mutations
export const ORDERDETAIL_GET_LOADER='ORDERDETAIL_GET_LOADER';//getters
export const ORDERDETAIL_MULTI_ITEMS_CHECKED='ORDERDETAIL_MULTI_ITEMS_CHECKED';//action
export const ORDERDETAIL_MULTI_ITEMS_ADD='ORDERDETAIL_MULTI_ITEMS_ADD';//mutations
export const ORDERDETAIL_MULTI_ITEMS_UNCHECKED='ORDERDETAIL_MULTI_ITEMS_UNCHECKED';//action
export const ORDERDETAIL_MULTI_ITEMS_REMOVE='ORDERDETAIL_MULTI_ITEMS_REMOVE';//mutations
export const ORDERDETAIL_GET_ALL_ITEMS_MULITCHECKED='ORDERDETAIL_GET_ALL_ITEMS_MULITCHECKED'//getters
export const ORDERDETAIL_UPDATE_SUGGESTED_DELIVERY_DATE='ORDERDETAIL_UPDATE_SUGGESTED_DELIVERY_DATE'//actions
export const ORDERDETAIL_UPDATE='ORDERDETAIL_UPDATE'//mutations
export const ORDERDETAIL_NEW_DELIVERY_DATE='ORDERDETAIL_NEW_DELIVERY_DATE'//actions


export const SELECT_MODULE='SELECT_MODULE/';//namespace
export const SET_CURRENT_SELECT='SET_CURRENT_SELECT';//mutations
export const GET_CURRENT_SELECT='GET_CURRENT_SELECT';//getters


export const SIDEBAR_MODULE='SIDEBAR_MODULE/'//namespace
export const SIDEBAR_SET_SLIDEIN='SIDEBAR_SET_SLIDEIN'//mutations
export const SIDEBAR_GET_SLIDEIN='SIDEBAR_GET_SLIDEIN'//gettes


export const ORDERDETAIL_SPLIT='ORDERDETAIL_SPLIT'//actions
export const ORDERDETAIL_SET_ITEMS='ORDERDETAIL_SPLIT'//mutations

export const PERMISSION_MODULE='PERMISSION_MODULE/'//namespace
export const PERMISSION_LOAD_LIST='PERMISSION_LOAD_LIST'//action
export const PERMISSION_GET_LIST='PERMISSION_GET_LIST'//getters
export const PERMISSION_SET_LIST='PERMISSION_SET_LIST'//mutations
export const PERMISSION_CHECKED='PERMISSION_CHECKED'//action
export const PERMISSION_UPDATE='PERMISSION_UPDATE'//mutations
export const PERMISSION_USER_PROFILE_CHECKED='PERMISSION_USER_PROFILE_CHECKED'//action
export const PERMISSION_USER_PROFILE_UPDATE='PERMISSION_USER_PROFILE_UPDATE'//mutations

export const NEWORDER_MODULE='NEWORDER_MODULE/'//namespace
export const NEWORDER_PRELOAD_FORM='NEWORDER_PRELOAD_FORM'//actions
export const NEWORDER_PRELOAD_FORM_SET='NEWORDER_PRELOAD_FORM_SET'//mutations
export const NEWORDER_PRELOAD_FORM_GET='NEWORDER_PRELOAD_FORM_GET'//getters
export const NEWORDER_PRELOAD_ORDER_GET='NEWORDER_PRELOAD_ORDER_GET'//getters
export const NEWORDER_GET_CUSTOMER='NEWORDER_GET_CUSTOMER'//actions
export const NEWORDER_PRELOAD_ORDER_CUSTOMER_SET='NEWORDER_PRELOAD_ORDER_CUSTOMER_SET'//mutations
export const NEWORDER_CUR_CUSTOMER = 'NEW_ORDER_CUR_CUSTOMER'//getters
export const NEWORDER_GET_ALL_TIMESLOTS = 'NEW_ORDER_GET_ALL_TIMESLOTS'//getters
export const NEW_ORDER_TRANCHE_POSTCODE = 'NEW_ORDER_TRANCHE_POSTCODE' //mutations
export const NEW_ORDER_SET_TRANCHE_POSTCODE = 'NEW_ORDER_SET_TRANCHE_POSTCODE' //actions
export const NEW_ORDER_GET_TRANCHE_POSTCODE = 'NEW_ORDER_GET_TRANCHE_POSTCODE' //getters
export const GET_CUSTOMER_DETAIL = 'GET_CUSTOMER_DETAIL' //getters
export const GET_LOADER_CLASS = 'GET_LOADER_CLASS' //getters
export const SET_LOADER_CLASS = 'SET_LOADER_CLASS' //getters


export const CUSTOMERLIST_MODULE='CUSTOMERLIST_MODULE/';//namespace
export const CUSTOMER_GET_LIST='CUSTOMER_GET_LIST'//getters
export const CUSTOMER_LOAD_LIST='CUSTOMER_LOAD_LIST';//action
export const CUSTOMER_SET_LOADER='CUSTOMER_SET_LOADER';//mutations
export const CUSTOMER_SET_LIST='CUSTOMER_SET_LIST'//mutations
export const CUSTOMER_GET_LOADER='CUSTOMER_GET_LOADER';//getters

// all customer page
export const CUSTOMER_MODULE='CUSTOMER_MODULE/';//namespace
export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST'; // getter
export const GET_LOADED_CUSTOMER_COUNT = 'GET_LOADED_CUSTOMER_COUNT'; // getter
export const GET_TOTAL_CUSTOMER_COUNT = 'GET_TOTAL_CUSTOMER_COUNT'; // getter
export const LOAD_MORE_CUSTOMER = 'LOAD_MORE_CUSTOMER'; // action and mutation
export const SET_CUSTOMER_LIST = 'SET_CUSTOMER_LIST'; // action and mutation
export const ADD_MORE_CUSTOMER_TO_LIST = 'ADD_MORE_CUSTOMER_TO_LIST'; //mutation
export const SET_CURRENT_SELECTED_CUSTOMER= 'SET_CURRENT_SELECTED_CUSTOMER'; //action
export const GET_CURRENT_SELECTED_CUSTOMER = 'GET_CURRENT_SELECTED_CUSTOMER'; //getter
export const GET_ALL_SELECTED_CUSTOMER = 'GET_ALL_SELECTED_CUSTOMER'; //getter
export const SET_CUSTOMER_DETAIL = 'SET_CUSTOMER_DETAIL'; //getter
export const SET_CUSTOMER_SELECTED_TAB = 'SET_CUSTOMER_SELECTED_TAB'; //action
export const SET_CUSTOMER_FILTER = 'SET_CUSTOMER_FILTER'; //action
export const FILTER_CUSTOMER_LIST = 'FILTER_CUSTOMER_LIST'; //action
export const LOAD_CUSTOMER_DETAIL = 'LOAD_CUSTOMER_DETAIL'; //action
// end all customer page

export const CUSTOMEREMAILS_GET_LIST='CUSTOMEREMAILS_GET_LIST'//getters
export const CUSTOMEREMAILS_SET_LIST='CUSTOMEREMAILS_SET_LIST';//mutations
export const CUSTOMERORDERS_GET_LIST='CUSTOMERORDERS_GET_LIST'//getters
export const CUSTOMERORDERS_SET_LIST='CUSTOMERORDERS_SET_LIST';//mutations

export const CUSTOMER_GET_SEARCH_LIST='CUSTOMER_GET_SEARCH_LIST'//getters
export const CUSTOMER_SEARCH_LOAD_LIST='CUSTOMER_SEARCH_LOAD_LIST';//action
export const CUSTOMER_SEARCH_SET_LIST='CUSTOMER_SEARCH_SET_LIST'//mutations
export const CUSTOMER_GET_SEARCH_COUNT='CUSTOMER_GET_SEARCH_COUNT'//getters
export const CUSTOMER_SEARCH_SET_COUNT='CUSTOMER_SEARCH_SET_COUNT'//mutations


export const SCAN_MODULE='SCAN_MODULE/'//namespace
export const SCAN_GET_ITEMS='SCAN_GET_ITEMS'//getters
export const SCAN_GET_BAGS='SCAN_GET_BAGS'//getters
export const SCAN_ITEM='SCAN_ITEM';//action
export const SCAN_SET_ITEMS='SCAN_SET_ITEMS';//mutations
export const SCAN_SET_BAGS='SCAN_SET_BAGS';//mutations


export const STATISTICS_MODULE='STATISTICS_MODULE/';//namespace
export const STATISTICS_SET_CURRENTTAB='STATISTICS_SET_CURRENTTAB';//action
export const SET_STATISTICS='SET_STATISTICS';//mutations
export const GET_STATISTICS='GET_STATISTICS';//getters
export const STATISTICS_LOAD_LIST='STATISTICS_LOAD_LIST';//action

export const DETAILING_MODULE='DETAILING_MODULE/';//namespace
export const SET_DETAILING='SET_DETAILING';//mutations
export const GET_DETAILING='GET_DETAILING';//getters
export const INIT_DETAILING='INIT_DETAILING';//action
export const UPDATE_DETAILING='UPDATE_DETAILING';//action
export const GET_DETAILING_LIST='GET_DETAILING_LIST';//getters
export const SET_DETAILING_LIST='SET_DETAILING_LIST';//mutations

export const SHIPPING_MODULE='SHIPPING_MODULE/'; //namespace
export const GET_PARTNERS='GET_PARTNERS'; //getters
export const SET_PARTNERS='SET_PARTNERS'; //mutation
export const SHIPPING_LOAD_LIST = 'SHIPPING_LOAD_LIST'; //action

// assembly home page types
export const ASSEMBLY_HOME_MODULE = 'ASSEMBLY_HOME_MODULE/'; //namespace
export const RESET_ASSEMBLY_STATE = 'RESET_ASSEMBLY_STATE'; //action
export const SET_ASSEMBLY_STATE = 'SET_ASSEMBLY_STATE'; //action
export const GET_ASSEMBLY_GROUPED_POSTES = 'GET_ASSEMBLY_GROUPED_POSTES';
export const GET_ASSEMBLY_MAIN_STATES = 'GET_ASSEMBLY_MAIN_STATES';
export const GET_STATS_TOTAL = 'GET_STATS_TOTAL';
export const GET_STATS_TODAY = 'GET_STATS_TODAY';
export const GET_STATS_TOMORROW = 'GET_STATS_TOMORROW';
export const GET_STATS_OVERDUE = 'GET_STATS_OVERDUE';
export const GET_STATS_LATER = 'GET_STATS_LATER';
export const GET_ASSEMBLY_INVOICE = 'GET_ASSEMBLY_INVOICE';
export const SET_ASSEMBLY_INVOICE = 'SET_ASSEMBLY_INVOICE';

// assembly home page Invoice
export const INVOICE_MODULE = 'INVOICE_MODULE/'; //namespace

export const SET_INVOICE_LIST = 'SET_INVOICE_LIST'; //action
export const SET_INVOICE_FILTER_FLAG = 'SET_INVOICE_FILTER_FLAG'; //action
export const SET_INVOICE_FILTER = 'SET_INVOICE_FILTER'; //action
export const FILTER_INVOICE_LIST = 'FILTER_INVOICE_LIST'; //action
export const LOAD_MORE_INVOICE = 'LOAD_MORE_INVOICE'; //action
export const ADD_MORE_INVOICE_TO_LIST = 'ADD_MORE_INVOICE_TO_LIST'; //mutation
export const SET_SELECTED_NAV = 'SET_SELECTED_NAV'; //mutation
export const GET_SELECTED_NAV = 'GET_SELECTED_NAV'; //mutation

export const GET_INVOICE_LIST = 'GET_INVOICE_LIST'; //getter
export const GET_TOTAL_INVOICE_COUNT = 'GET_TOTAL_INVOICE_COUNT'; //getter
export const GET_LOADED_INVOICE_COUNT = 'GET_LOADED_INVOICE_COUNT'; //getter
export const GET_INVOICE_STATUS = 'GET_INVOICE_STATUS'; //getter
export const GET_INVOICE_DESTINATION = 'GET_INVOICE_DESTINATION'; //getter
export const GET_INVOICE_LOCATION = 'GET_INVOICE_LOCATION'; //getter

export const INVOICELIST_GET_CURRENT_SELECTED = 'INVOICELIST_GET_CURRENT_SELECTED'; //getter
export const INVOICELIST_GET_ALL_SELECTED = 'INVOICELIST_GET_ALL_SELECTED'; //getter

export const INVOICELIST_SET_CURRENT_SELECTED = 'INVOICELIST_SET_CURRENT_SELECTED'; //action | mutation
export const INVOICELIST_SET_ALL_SELECTED = 'INVOICELIST_SET_ALL_SELECTED'; //action | mutation
export const INVOICELIST_SET_MULTI_UNCHECKED = 'INVOICELIST_SET_MULTI_UNCHECKED'; //action | mutation

export const INVOICE_RESET_MULITCHECKED = 'INVOICE_RESET_MULITCHECKED'; //action | mutation

// item detail page contant

export const ITEM_DETAIL_MODULE = 'ITEM_DETAIL_MODULE/'; //action | mutation
export const ITEM_DETAIL_LOAD_DETAIL = 'ITEM_DETAIL_LOAD_DETAIL'; //action

export const ITEM_DETAIL_GET_LOADER = 'ITEM_DETAIL_GET_LOADER'; //action | mutation
export const ITEM_DETAIL_SET_LOADER = 'ITEM_DETAIL_SET_LOADER'; //action | mutation

export const ITEM_DETAIL_SET_DETAIL = 'ITEM_DETAIL_SET_DETAIL'; //action | mutation
export const ITEM_DETAIL_GET_DETAIL = 'ITEM_DETAIL_GET_DETAIL'; //action | mutation