export const  LOADER_MODULE='LOADER_MODULE/'; //namespace
export const  SET_SHOW_LOADER = 'SET_SHOW_LOADER';//mutations
export const  SET_LOADER_MSG='SET_LOADER_MSG'; //mutations
export const  GET_SHOW_LOADER = 'GET_SHOW_LOADER'; //getters
export const  GET_LOADER_MSG='GET_LOADER_MSG';// getters
export const  DISPLAY_LOADER ='DISPLAY_LOADER';//actions
export const  HIDE_LOADER ='HIDE_LOADER';//actions


export const ORDERLIST_MODULE='ORDERLIST_MODULE/';//namespace
export const ORDERLIST_SET_CURRENTTAB='ORDERLIST_SET_CURRENTTAB';//action
export const ORDERLIST_CURRENTTAB='ORDERLIST_CURRENTTAB';//mutations
export const ORDERLIST_GET_LIST='ORDERLIST_GET_LIST';//getters
export const ORDERLIST_LOAD_LIST='ORDERLIST_LOAD_LIST';//action

export const ORDERLIST_ADD_TO_LIST='ORDERLIST_ADD_TO_LIST';//mutations
export const ORDERLIST_SHOWMORE_LIST='ORDERLIST_SHOWMORE_LIST'//mutations
export const ORDERLIST_SET_CURRENT_SELECTED='ORDERLIST_SET_CURRENT_SELECTED'//mutations
export const ORDERLIST_GET_CURRENT_SELECTED='ORDERLIST_GET_CURRENT_SELECTED'//getters
export const ORDERLIST_SELECT_CURRENT='ORDERLIST_SELECT_CURRENT'//action
export const ORDERLIST_SET_ALL_ORDER_MULITCHECKED='ORDERLIST_SET_ALL_ORDER_MULITCHECKED'//mutations
export const ORDERLIST_GET_ALL_ORDER_MULITCHECKED='ORDERLIST_GET_ALL_ORDER_MULITCHECKED'//getters
export const ORDERLIST_MULITCHECKED='ORDERLIST_MULITCHECKED'//action
export const ORDERLIST_MULITUNCHECKED='ORDERLIST_MULITUNCHECKED'//action
export const ORDERLIST_SET_MULITCHECKED='ORDERLIST_SET_MULITCHECKED'//mutations
export const ORDERLIST_RESET_MULITCHECKED='ORDERLIST_RESET_MULITCHECKED'//actions
export const ORDERLIST_SORT='ORDERLIST_SORT'//action
export const ORDERLIST_GET_SORT='ORDERLIST_GET_SORT'//getters
export const ORDERLIST_SET_SORT='ORDERLIST_SET_SORT'//mutations
export const ORDERLIST_SET_LIMIT='ORDERLIST_SET_LIMIT'//mutations
export const ORDERLIST_RESET_ORDERLIST='ORDERLIST_RESET_ORDERLIST'//mutations
export const ORDERLIST_SET_LOADERMSG='ORDERLIST_SET_LOADERMSG'//mutations
export const ORDERLIST_LOADERMSG='ORDERLIST_LOADERMSG'//action
export const ORDERLIST_FILTER='ORDERLIST_FILTER'//action
export const ORDERLIST_SET_FILTER='ORDERLIST_SET_FILTER'//mutations
export const ORDERLIST_GET_FILTER='ORDERLIST_GET_FILTER'//getters
export const ORDERLIST_CANCEL_ORDERS='ORDERLIST_CANCEL_ORDERS'//action
export const ORDERLIST_MARK_AS_LATE='ORDERLIST_MARK_AS_LATE'//action
export const ORDERLIST_UPDATE_STATUS='ORDERLIST_UPDATE_STATUS'//mutations
export const ORDERLIST_REMOVE_ORDERS='ORDERLIST_REMOVE_ORDERS'//mutations
export const ORDERLIST_LOAD_TAB='ORDERLIST_LOAD_TAB'//action
export const ORDERLIST_UPDATE_SUGGESTED_DELIVERY_DATE='ORDERLIST_UPDATE_SUGGESTED_DELIVERY_DATE'//mutations
export const ORDERLIST_NEW_DELIVERY_DATE=''//mutations


export const TOASTER_MODULE='TOASTER_MODULE/';//namespace
export const TOASTER_ADD_TOAST='TOASTER_ADD_TOAST';//mutations
export const TOASTER_REMOVE_TOAST='TOASTER_REMOVE_TOAST';//mutations
export const TOASTER_MESSAGE='TOASTER_MESSAGE';//action
export const TOASTER_GET_ALL='TOASTER_GET_ALL';//getters


export const ORDERDETAIL_MODULE='ORDERDETAIL_MODULE/';//namespace
export const ORDERDETAIL_GET_DETAILS='ORDERDETAIL_GET_DETAILS'//getters
export const ORDERDETAIL_LOAD_DETAIL='ORDERDETAIL_LOAD_DETAIL';//action
export const ORDERDETAIL_SET_LOADER='ORDERDETAIL_SET_LOADER';//mutations
export const ORDERDETAIL_SET_DETAILS='ORDERDETAIL_SET_DETAILS'//mutations
export const ORDERDETAIL_GET_LOADER='ORDERDETAIL_GET_LOADER';//getters
export const ORDERDETAIL_MULTI_ITEMS_CHECKED='ORDERDETAIL_MULTI_ITEMS_CHECKED';//action
export const ORDERDETAIL_MULTI_ITEMS_ADD='ORDERDETAIL_MULTI_ITEMS_ADD';//mutations
export const ORDERDETAIL_MULTI_ITEMS_UNCHECKED='ORDERDETAIL_MULTI_ITEMS_UNCHECKED';//action
export const ORDERDETAIL_MULTI_ITEMS_REMOVE='ORDERDETAIL_MULTI_ITEMS_REMOVE';//mutations
export const ORDERDETAIL_GET_ALL_ITEMS_MULITCHECKED='ORDERDETAIL_GET_ALL_ITEMS_MULITCHECKED'//getters
export const ORDERDETAIL_UPDATE_SUGGESTED_DELIVERY_DATE='ORDERDETAIL_UPDATE_SUGGESTED_DELIVERY_DATE'//actions
export const ORDERDETAIL_UPDATE='ORDERDETAIL_UPDATE'//mutations
export const ORDERDETAIL_NEW_DELIVERY_DATE='ORDERDETAIL_NEW_DELIVERY_DATE'//actions


export const SELECT_MODULE='SELECT_MODULE/';//namespace
export const SET_CURRENT_SELECT='SET_CURRENT_SELECT';//mutations
export const GET_CURRENT_SELECT='GET_CURRENT_SELECT';//getters


export const SIDEBAR_MODULE='SIDEBAR_MODULE/'//namespace
export const SIDEBAR_SET_SLIDEIN='SIDEBAR_SET_SLIDEIN'//mutations
export const SIDEBAR_GET_SLIDEIN='SIDEBAR_GET_SLIDEIN'//gettes


export const ORDERDETAIL_SPLIT='ORDERDETAIL_SPLIT'//actions
export const ORDERDETAIL_SET_ITEMS='ORDERDETAIL_SPLIT'//mutations

export const PERMISSION_MODULE='PERMISSION_MODULE/'//namespace
export const PERMISSION_LOAD_LIST='PERMISSION_LOAD_LIST'//action
export const PERMISSION_GET_LIST='PERMISSION_GET_LIST'//getters
export const PERMISSION_SET_LIST='PERMISSION_SET_LIST'//mutations
export const PERMISSION_CHECKED='PERMISSION_CHECKED'//action
export const PERMISSION_UPDATE='PERMISSION_UPDATE'//mutations
export const PERMISSION_USER_PROFILE_CHECKED='PERMISSION_USER_PROFILE_CHECKED'//action
export const PERMISSION_USER_PROFILE_UPDATE='PERMISSION_USER_PROFILE_UPDATE'//mutations

export const NEWORDER_MODULE='NEWORDER_MODULE/'//namespace
export const NEWORDER_PRELOAD_FORM='NEWORDER_PRELOAD_FORM'//actions
export const NEWORDER_PRELOAD_FORM_SET='NEWORDER_PRELOAD_FORM_SET'//mutations
export const NEWORDER_PRELOAD_FORM_GET='NEWORDER_PRELOAD_FORM_GET'//getters
export const NEWORDER_PRELOAD_ORDER_GET='NEWORDER_PRELOAD_ORDER_GET'//getters
export const NEWORDER_GET_CUSTOMER='NEWORDER_GET_CUSTOMER'//actions
export const NEWORDER_PRELOAD_ORDER_CUSTOMER_SET='NEWORDER_PRELOAD_ORDER_CUSTOMER_SET'//mutations


export const CUSTOMERLIST_MODULE='CUSTOMERLIST_MODULE/';//namespace
export const CUSTOMER_GET_LIST='CUSTOMER_GET_LIST'//getters
export const CUSTOMER_LOAD_LIST='CUSTOMER_LOAD_LIST';//action
export const CUSTOMER_SET_LOADER='CUSTOMER_SET_LOADER';//mutations
export const CUSTOMER_SET_LIST='CUSTOMER_SET_LIST'//mutations
export const CUSTOMER_GET_LOADER='CUSTOMER_GET_LOADER';//getters

export const CUSTOMEREMAILS_GET_LIST='CUSTOMEREMAILS_GET_LIST'//getters
export const CUSTOMEREMAILS_SET_LIST='CUSTOMEREMAILS_SET_LIST';//mutations
export const CUSTOMERORDERS_GET_LIST='CUSTOMERORDERS_GET_LIST'//getters
export const CUSTOMERORDERS_SET_LIST='CUSTOMERORDERS_SET_LIST';//mutations

export const CUSTOMER_GET_SEARCH_LIST='CUSTOMER_GET_SEARCH_LIST'//getters
export const CUSTOMER_SEARCH_LOAD_LIST='CUSTOMER_SEARCH_LOAD_LIST';//action
export const CUSTOMER_SEARCH_SET_LIST='CUSTOMER_SEARCH_SET_LIST'//mutations
export const CUSTOMER_GET_SEARCH_COUNT='CUSTOMER_GET_SEARCH_COUNT'//getters
export const CUSTOMER_SEARCH_SET_COUNT='CUSTOMER_SEARCH_SET_COUNT'//mutations


export const SCAN_MODULE='SCAN_MODULE/'//namespace
export const SCAN_GET_ITEMS='SCAN_GET_ITEMS'//getters
export const SCAN_GET_BAGS='SCAN_GET_BAGS'//getters
export const SCAN_ITEM='SCAN_ITEM';//action
export const SCAN_SET_ITEMS='SCAN_SET_ITEMS';//mutations
export const SCAN_SET_BAGS='SCAN_SET_BAGS';//mutations


export const STATISTICS_MODULE='STATISTICS_MODULE/';//namespace
export const STATISTICS_SET_CURRENTTAB='STATISTICS_SET_CURRENTTAB';//action
export const SET_STATISTICS='SET_STATISTICS';//mutations
export const GET_STATISTICS='GET_STATISTICS';//getters
export const STATISTICS_LOAD_LIST='STATISTICS_LOAD_LIST';//action

export const DETAILING_MODULE='DETAILING_MODULE/';//namespace
export const SET_DETAILING='SET_DETAILING';//mutations
export const GET_DETAILING='GET_DETAILING';//getters
export const INIT_DETAILING='INIT_DETAILING';//action
export const UPDATE_DETAILING='UPDATE_DETAILING';//action