export const  LOADER_MODULE='LOADER_MODULE/'; //namespace
export const  SET_SHOW_LOADER = 'SET_SHOW_LOADER';//mutations
export const  SET_LOADER_MSG='SET_LOADER_MSG'; //mutations
export const  GET_SHOW_LOADER = 'GET_SHOW_LOADER'; //getters
export const  GET_LOADER_MSG='GET_LOADER_MSG';// getters
export const  DISPLAY_LOADER ='DISPLAY_LOADER';//actions
export const  HIDE_LOADER ='HIDE_LOADER';//actions


export const ORDERLIST_MODULE='ORDERLIST_MODULE/';//namespace
export const ORDERLIST_SET_CURRENTTAB='ORDERLIST_SET_CURRENTTAB';//action
export const ORDERLIST_CURRENTTAB='ORDERLIST_CURRENTTAB';//mutations
export const ORDERLIST_GET_LIST='ORDERLIST_GET_LIST';//getters
export const ORDERLIST_LOAD_LIST='ORDERLIST_LOAD_LIST';//action

export const ORDERLIST_ADD_TO_LIST='ORDERLIST_ADD_TO_LIST';//mutations
export const ORDERLIST_SHOWMORE_LIST='ORDERLIST_SHOWMORE_LIST'//mutations
export const ORDERLIST_SET_CURRENT_SELECTED='ORDERLIST_SET_CURRENT_SELECTED'//mutations
export const ORDERLIST_GET_CURRENT_SELECTED='ORDERLIST_GET_CURRENT_SELECTED'//getters
export const ORDERLIST_SELECT_CURRENT='ORDERLIST_SELECT_CURRENT'//action
export const ORDERLIST_SET_ALL_ORDER_MULITCHECKED='ORDERLIST_SET_ALL_ORDER_MULITCHECKED'//mutations
export const ORDERLIST_GET_ALL_ORDER_MULITCHECKED='ORDERLIST_GET_ALL_ORDER_MULITCHECKED'//getters
export const ORDERLIST_MULITCHECKED='ORDERLIST_MULITCHECKED'//action
export const ORDERLIST_MULITUNCHECKED='ORDERLIST_MULITUNCHECKED'//action
export const ORDERLIST_SET_MULITCHECKED='ORDERLIST_SET_MULITCHECKED'//mutations
export const ORDERLIST_RESET_MULITCHECKED='ORDERLIST_RESET_MULITCHECKED'//actions
export const ORDERLIST_SORT='ORDERLIST_SORT'//action
export const ORDERLIST_GET_SORT='ORDERLIST_GET_SORT'//getters
export const ORDERLIST_SET_SORT='ORDERLIST_SET_SORT'//mutations
export const ORDERLIST_SET_LIMIT='ORDERLIST_SET_LIMIT'//mutations
export const ORDERLIST_RESET_ORDERLIST='ORDERLIST_RESET_ORDERLIST'//mutations
export const ORDERLIST_SET_LOADERMSG='ORDERLIST_SET_LOADERMSG'//mutations
export const ORDERLIST_LOADERMSG='ORDERLIST_LOADERMSG'//action
export const ORDERLIST_FILTER='ORDERLIST_FILTER'//action
export const ORDERLIST_SET_FILTER='ORDERLIST_SET_FILTER'//mutations
export const ORDERLIST_GET_FILTER='ORDERLIST_GET_FILTER'//getters
export const ORDERLIST_CANCEL_ORDERS='ORDERLIST_CANCEL_ORDERS'//action
export const ORDERLIST_MARK_AS_LATE='ORDERLIST_MARK_AS_LATE'//action
export const ORDERLIST_UPDATE_STATUS='ORDERLIST_UPDATE_STATUS'//mutations
export const ORDERLIST_REMOVE_ORDERS='ORDERLIST_REMOVE_ORDERS'//mutations
export const ORDERLIST_LOAD_TAB='ORDERLIST_LOAD_TAB'//action



export const TOASTER_MODULE='TOASTER_MODULE/';//namespace
export const TOASTER_ADD_TOAST='TOASTER_ADD_TOAST';//mutations
export const TOASTER_REMOVE_TOAST='TOASTER_REMOVE_TOAST';//mutations
export const TOASTER_MESSAGE='TOASTER_MESSAGE';//action
export const TOASTER_GET_ALL='TOASTER_GET_ALL';//getters